apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-static-site.fullname" . }}
  labels:
    app: {{ include "my-static-site.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 31693 }}
      {{- end }}
  selector:
    app: {{ include "my-static-site.name" . }}
