apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-static-site.fullname" . }}
  labels:
    app: {{ include "my-static-site.name" . }} 
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 31693
  selector:
    app: {{ include "my-static-site.name" . }}
