apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-static-site.fullname" . }}
  labels:
    release: prometheus-stack  
spec:
  selector:
    matchLabels:
      app: {{ include "my-static-site.name" . }}
  endpoints:
    - port: http
      interval: 15s
