# test-simple-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'nginx_http_requests_total'
      resources:
        template: "<<.Resource>>"
      name:
        matches: ".*"
        as: "nginx_test_metric"
      metricsQuery: '<<.Series>>'
