apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: monitoring   # тот же namespace, где стоит kube-prometheus-stack
  labels:
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/component: config
data:
  config.yaml: |
    rules:
      default: false
      custom:
        # Берём nginx_http_requests_total и превращаем в http_requests_total (RPS)
        - seriesQuery: 'nginx_http_requests_total'
          resources:
            overrides:
              namespace:
                resource: namespace
              pod:
                resource: pod
          name:
            matches: ".*"
            as: "http_requests_total"
          metricsQuery: rate(nginx_http_requests_total[1m])
