apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-simple-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: my-static-site-my-static-site
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15           
  cooldownPeriod: 30            
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60  
          policies:
          - type: Pods
            value: 1
            periodSeconds: 30   
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15 
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-stack-kube-prom-prometheus.monitoring.svc:9090
      metricName: nginx_total_requests
      threshold: '5'
      query: 'sum(rate(nginx_ingress_controller_nginx_process_requests_total[2m]))'