prometheus:
  url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc
  port: 9090

rules:
  default: true
  external:
  - seriesQuery: 'nginx_ingress_controller_nginx_process_requests_total'
    resources:
      overrides:
        namespace:
          resource: "namespace"
    name:
      as: "nginx_global_rps"
    metricsQuery: 'sum(rate(nginx_ingress_controller_nginx_process_requests_total[2m]))'