replicaCount: 1

image:
  repository: my-static-nginx
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  nodePort: 31693   # применяется, если type=NodePort

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

grafana:
  expose: true
  nodePort: 30300


hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetAverageValue: "5000m"  
  up_stabilizationWindowSeconds: 60
  down_stabilizationWindowSeconds: 30




prometheus:
  enabled: true
