replicaCount: 1

image:
  repository: my-static-nginx
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m      
    memory: 32Mi
  limits:
    cpu: 100m     
    memory: 64Mi


grafana:
  expose: true
  nodePort: 30300

