replicaCount: 1

image:
  repository: my-static-nginx
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 5m
    memory: 8Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40

